name: Doxygen GitHub Pages Deploy Action

on:
  push: {}

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: doxygen-pages-${{ github.ref_name }}
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_folder: "docs/${{ github.ref_name }}"
